services:
  prom:
    image: "prom/prometheus:latest"
    volumes:
      - .:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - "9090:9090"
  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    depends_on:
      - prom
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
  hello:
    build: .
    ports:
      - "8080:8080"
