scrape_configs:
  - job_name: 'hello'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'hello:8080' ]

  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:9090' ]
